name: Nodejs CI

on: [ push ]

jobs:
  builds:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run build
    - run: npm run test
    - run: npm run test:e2e
      env:
        CI: true